### PR TITLE
Fix slice patch loading

### PR DESCRIPTION
**Pull request by cbush**
Hi, thanks for the great library! I noticed that 9-patches were not loading correctly in my project. According to [the spec](https://github.com/aseprite/aseprite/blob/master/docs/ase-file-specs.md), slice chunk flag 1 == "It's a 9-patches slice". I think this should fix it.

### CODE REVIEW

**Comment by cbush** [comment]
@TheCyberRonin ICYMI

**Comment by TheCyberRonin** [comment]
Oh my! I'm so sorry, I'll review this this evening and get it pushed!

**Review by TheCyberRonin — APPROVED** [review]
Appreciate the work. Sorry I missed it, I'll have to readjust my notifications so I get emails now. I have a personal and work GitHub and I find myself not signing in as much on my personal

**Comment by cbush** [comment]
No problem! Thanks for taking a look. I actually noticed an issue someone raised on one of my repos that I didn't get a notification for. So I realized I might just need to tag you.

**Pull request merged**
